version: '1.0'

services:
  appServer:
    image: mysql
    container_name: 'mysql'

    environment:
      spring.datasource.url: 'jdbc:mysql://db:3306/mysql'
      spring.jpa.hibernate.ddl-auto: 'create-drop'

    ports:
      - '8080:8080'

    depends_on:
      - db

  db:
    image: mysql

    environment:
      mysql_user: root
      mysql_password: mysql
      MYSQL_DB: mysql